# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &defaults
  adapter: postgresql
  encoding: unicode
  database: sdruby_development
  pool: 20
  username: root
  password:
  host: localhost
  port: 5432

test:
  <<: *defaults
  database: sdruby_test

staging:
  <<: *defaults
  database: sdruby_staging

production:
  <<: *defaults
  database: sdruby_production

