development: &defaults
  adapter: postgresql
  encoding: unicode
  database: sdruby_development
  pool: 20
  username: root
  password:
  host: localhost
  port: 5432

test:
  <<: *defaults
  database: sdruby_test

staging:
  <<: *defaults
  database: sdruby_staging

production:
  <<: *defaults
  database: sdruby_production

